# Generated by Django 5.0.4 on 2025-10-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_last_password_change_user_must_change_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="must_change_password",
            new_name="is_first_login",
        ),
    ]
