# Generated by Django 5.0.4 on 2025-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_must_change_password_user_is_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="profession_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website_address",
            field=models.URLField(blank=True),
        ),
    ]
