# Generated by Django 5.0.4 on 2026-03-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_user_is_team_lead"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendRequest",
        ),
    ]
