# Generated by Django 5.0.4 on 2026-03-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_delete_friendrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupProfile",
        ),
    ]
