# Generated by Django 5.0.4 on 2026-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_section_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
