# Generated by Django 5.0.4 on 2026-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("team_leader", "Team Leader"),
                    ("editor", "Editor"),
                    ("admin", "Admin"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
