# Generated by Django 5.0.4 on 2026-04-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_group_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group_name",
        ),
    ]
