# Generated by Django 5.0.4 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_user_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
