# Generated by Django 5.2.7 on 2025-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(choices=[('warm_discussion', 'Warm Discussion'), ('drama', 'Drama'), ('event_report', 'Event Report'), ('recommendation', 'Recommendation'), ('trending', 'Trending'), ('breaking', 'Breaking News'), ('latest', 'Latest Updates')], max_length=32)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/images/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('from_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MediaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('kind', models.CharField(choices=[('card', 'Card'), ('photo', 'Photo'), ('gallery', 'Gallery')], default='card', max_length=16)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/images/')),
                ('image_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cards/covers/')),
                ('cover_image_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('writer', models.CharField(max_length=255)),
                ('writer_avatar', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('read_time', models.CharField(blank=True, max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='readings/images/')),
                ('image_url', models.URLField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-publish_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/avatars/')),
                ('avatar_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TvProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('air_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tv/images/')),
                ('image_url', models.URLField(blank=True)),
                ('writer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-air_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=100)),
                ('video_type', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('video_url', models.URLField()),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WeeklyMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=32)),
                ('status_label', models.CharField(max_length=32)),
                ('status_color', models.CharField(blank=True, max_length=32)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='weekly/images/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
    ]
