# Generated by Django 5.0.4 on 2026-03-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/avatars/')),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Accepts: .doc, .docx, .pdf, .ppt, .pptx, and other document formats', upload_to='content/attachments/')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_event', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LearnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name in the specified language', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('learn_type', models.CharField(blank=True, choices=[('cards', 'Cards'), ('posters', 'Posters')], default='cards', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering (lower values appear first)')),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MyListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='infowebsite/logos/')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='photo-collections/photos/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of photo in the collection')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo-collections/covers/')),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-happened_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RelatedReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.JSONField(blank=True, default=list)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RelatedReportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(blank=True, choices=[('clip_video', 'Clip Video'), ('full_video', 'Full Video')], max_length=100, null=True)),
                ('language', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('thumbnail_url', models.JSONField(blank=True, default=list)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('video_url', models.URLField()),
                ('guest_speakers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('-happened_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name in the specified language', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering (lower values appear first)')),
            ],
            options={
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LatestNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='latest-news/images/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of image in the news item')),
                ('latest_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.latestnews')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='EventCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('guest_speakers', models.JSONField(blank=True, default=list)),
                ('live_stream_link', models.URLField(blank=True, null=True)),
                ('start_event_date', models.DateField(blank=True, null=True)),
                ('start_event_time', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=64, null=True)),
                ('learn', models.ForeignKey(blank=True, limit_choices_to={'category__learn_type': 'posters'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_communities', to='content.learn')),
            ],
            options={
                'ordering': ('-start_event_date', '-start_event_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='learncategory',
            constraint=models.UniqueConstraint(fields=('name', 'learn_type'), name='unique_learncategory_name_per_type'),
        ),
        migrations.AddField(
            model_name='learn',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learns', to='content.learncategory'),
        ),
        migrations.AddField(
            model_name='mylistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.photocollection'),
        ),
        migrations.AddField(
            model_name='relatedreports',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_reports', to='content.relatedreportscategory'),
        ),
        migrations.AddField(
            model_name='mylistentry',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='content.video'),
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='Video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.video'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.videocategory'),
        ),
        migrations.AddConstraint(
            model_name='latestnewsimage',
            constraint=models.UniqueConstraint(fields=('latest_news', 'order'), name='unique_image_order_per_news'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('collection', 'order'), name='unique_photo_order_per_collection'),
        ),
        migrations.AlterUniqueTogether(
            name='mylistentry',
            unique_together={('user', 'video')},
        ),
    ]
