# Generated by Django 5.0.4 on 2025-10-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyentry",
            options={"ordering": ("story_date", "title")},
        ),
        migrations.RenameField(
            model_name="historyentry",
            old_name="from_date",
            new_name="story_date",
        ),
        migrations.RemoveField(
            model_name="historyentry",
            name="to_date",
        ),
    ]
