# Generated by Django 5.0.4 on 2026-03-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="latestnews",
            name="image",
        ),
        migrations.RemoveField(
            model_name="latestnews",
            name="image_url",
        ),
        migrations.CreateModel(
            name="LatestNewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="latest-news/images/")),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of image in the news item"
                    ),
                ),
                (
                    "latest_news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.latestnews",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="latestnewsimage",
            constraint=models.UniqueConstraint(
                fields=("latest_news", "order"), name="unique_image_order_per_news"
            ),
        ),
    ]
