# Generated by Django 5.0.4 on 2026-03-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0002_remove_latestnews_image_remove_latestnews_image_url_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatedreports",
            old_name="thumnail_url",
            new_name="thumbnail_url",
        ),
    ]
