# Generated by Django 5.0.4 on 2025-10-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_historyentry_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reading",
        ),
    ]
