# Generated by Django 5.0.4 on 2025-10-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_delete_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
