# Generated by Django 5.0.4 on 2026-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_latestnews_add_is_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="photocollection",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
