# Generated by Django 5.0.4 on 2025-10-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_eventcategory_postcategory_tvprogramcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediacard",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="video",
            name="subject",
        ),
    ]
