# Generated by Django 5.0.4 on 2026-03-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_photocollection_is_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="latestnews",
            name="is_test",
        ),
    ]
