# Generated by Django 5.0.4 on 2026-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_remove_latestnews_is_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestnews",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
