# Generated by Django 5.0.4 on 2025-10-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_positionteammember_alter_teammember_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="author",
            new_name="writer",
        ),
    ]
