# Generated by Django 5.0.4 on 2026-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_latestnews_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedreports",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="related-reports/images/"
            ),
        ),
    ]
