# Generated by Django 5.0.4 on 2026-03-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_relatedreports_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedreports",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
