# Generated by Django 5.0.4 on 2025-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_rename_author_event_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="positionteammember",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tvprogramcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="videocategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
