# Generated by Django 5.0.4 on 2026-03-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_relatedreports_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyListEntry",
        ),
    ]
