# Generated by Django 5.0.4 on 2025-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_eventcategory_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MediaCard",
        ),
    ]
