# Generated by Django 5.0.4 on 2026-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_delete_mylistentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="our-team/images/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
