# Generated by Django 5.0.4 on 2025-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_delete_mediacard"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                blank=True,
                choices=[("card", "Card"), ("photo", "Photo"), ("reading", "Reading")],
                default="card",
                max_length=100,
            ),
        ),
    ]
