# Generated by Django 5.0.4 on 2025-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_post_image_post_image_url_post_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="camera_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="cast",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="season",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
