# Generated by Django 5.0.4 on 2026-03-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_ourteam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourteam",
            name="image_url",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="OurTeamImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="our-team/images/")),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of image for the team member"
                    ),
                ),
                (
                    "our_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.ourteam",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="ourteamimage",
            constraint=models.UniqueConstraint(
                fields=("our_team", "order"), name="unique_image_order_per_team_member"
            ),
        ),
    ]
