# Generated by Django 5.0.4 on 2025-10-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_post_camera_name_post_country_video_cast_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cast",
            field=models.TextField(blank=True, default=list),
        ),
    ]
