# Generated by Django 5.0.4 on 2026-03-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_alter_ourteam_image_url_ourteamimage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Authors",
        ),
    ]
