# Generated by Django 5.0.4 on 2026-03-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_delete_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="books/images/"),
                ),
                (
                    "cover_image",
                    models.FileField(blank=True, null=True, upload_to="books/covers/"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="books/reviews/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of review image in the book"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="content.book",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="bookreview",
            constraint=models.UniqueConstraint(
                fields=("book", "order"), name="unique_review_order_per_book"
            ),
        ),
    ]
