# Generated by Django 5.0.4 on 2025-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_alter_video_cast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cast",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
