# Generated by Django 5.0.4 on 2025-10-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_video_cast"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ("-happened_at", "-created_at")},
        ),
        migrations.RenameField(
            model_name="video",
            old_name="published_at",
            new_name="happened_at",
        ),
    ]
