# Generated by Django 5.0.4 on 2026-03-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_ourhistory_yearsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="HistoryYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ("-year",),
            },
        ),
        migrations.RemoveField(
            model_name="yearsection",
            name="our_history",
        ),
        migrations.CreateModel(
            name="HistoryEventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="our-history/images/")),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.historyevent",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="historyevent",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="content.historyyear",
            ),
        ),
        migrations.DeleteModel(
            name="OurHistory",
        ),
        migrations.DeleteModel(
            name="YearSection",
        ),
        migrations.AddConstraint(
            model_name="historyeventimage",
            constraint=models.UniqueConstraint(
                fields=("event", "order"), name="unique_image_order_per_event"
            ),
        ),
    ]
