# Generated by Django 5.0.4 on 2025-10-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_eventsection_alter_event_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-happened_at", "title")},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="happened_at",
        ),
    ]
