# Generated by Django 5.0.4 on 2026-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_historyevent_historyyear_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyevent",
            name="sub_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
