# Generated by Django 5.0.4 on 2026-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_historyevent_sub_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyevent",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelOptions(
            name="historyevent",
            options={"ordering": ("year",)},
        ),
        migrations.DeleteModel(
            name="HistoryYear",
        ),
    ]
