# Generated by Django 5.0.4 on 2026-03-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_alter_historyevent_year_alter_historyevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyeventimage",
            name="caption",
            field=models.CharField(max_length=1000),
        ),
    ]
