# Generated by Django 5.0.4 on 2025-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_eventcomment_postcomment_tvprogramcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="postlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tvprogramlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="videolike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="weeklymomentlike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
