# Generated by Django 5.0.4 on 2025-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_eventlike_updated_at_postlike_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvprogram",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
