# Generated by Django 5.0.4 on 2026-03-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_alter_historyeventimage_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourteam",
            name="is_heart",
            field=models.BooleanField(default=False),
        ),
    ]
