# Generated by Django 5.0.4 on 2026-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_ourteam_is_heart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyevent",
            options={"ordering": ("year", "month")},
        ),
        migrations.AddField(
            model_name="historyevent",
            name="month",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
