# Generated by Django 5.2.7 on 2025-10-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_tvprogram_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
