# Generated by Django 5.0.4 on 2026-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_alter_historyevent_options_historyevent_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historyevent",
            old_name="sub_title",
            new_name="sub_title_one",
        ),
        migrations.AddField(
            model_name="historyevent",
            name="sub_title_two",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
