# Generated by Django 5.0.4 on 2025-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_alter_post_options_remove_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(
                choices=[("full_video", "Full Video"), ("unit_video", "Unit Video")],
                default="full_video",
                max_length=100,
            ),
        ),
    ]
