# Generated by Django 5.0.4 on 2025-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_alter_video_video_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("videos", "Videos"),
                    ("reports", "Reports"),
                    ("news", "News"),
                ],
                default="news",
                max_length=50,
            ),
        ),
    ]
