# Generated by Django 5.0.4 on 2026-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_rename_sub_title_historyevent_sub_title_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learn",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="learn",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
