# Generated by Django 5.0.4 on 2026-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_alter_learn_subtitle_alter_learn_title"),
        ("content", "0023_video_base_video"),
    ]

    operations = []
