# Generated by Django 5.0.4 on 2026-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_merge_20260407_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="learn",
            name="another_contry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="learn",
            name="guest_speakers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
