# Generated by Django 5.0.4 on 2025-10-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_comments_reply_like_likecomment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likecomment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="likecomment",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="likecomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="LikeComment",
        ),
    ]
