# Generated by Django 5.0.4 on 2026-04-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_learn_another_contry_learn_guest_speakers"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCommunityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="event-community/images/")),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of image in the event"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.eventcommunity",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "created_at"),
            },
        ),
    ]
