# Generated by Django 5.0.4 on 2026-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_eventcommunityimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learn",
            old_name="another_contry",
            new_name="author_country",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="guest_speakers",
        ),
        migrations.AddField(
            model_name="learn",
            name="author_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
