# Generated by Django 5.0.4 on 2025-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cast",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="events/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
    ]
