# Generated by Django 5.0.4 on 2026-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_rename_another_contry_learn_author_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcommunityimage",
            name="caption",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
