# Generated by Django 5.0.4 on 2026-04-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_alter_eventcommunityimage_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventcommunity",
            name="learn",
        ),
    ]
