# Generated by Django 5.0.4 on 2025-10-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_event_cast_event_tags_event_thumbnail_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TvProgram",
        ),
        migrations.DeleteModel(
            name="TvProgramCategory",
        ),
    ]
