# Generated by Django 5.0.4 on 2025-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_delete_tvprogram_delete_tvprogramcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historyentry",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklymoment",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
