# Generated by Django 5.0.4 on 2026-04-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_remove_eventcommunity_learn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learn",
            name="is_event",
        ),
    ]
