# Generated by Django 5.0.4 on 2026-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_remove_learn_is_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcommunity",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
