# Generated by Django 5.0.4 on 2025-10-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_mylistentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
