# Generated by Django 5.0.4 on 2025-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_postrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="series",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="video",
            name="season",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
