# Generated by Django 5.0.4 on 2026-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_historical_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallearn",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalvideo",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learn",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
