# Generated by Django 5.0.4 on 2025-10-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_seasontitle_alter_video_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="series",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
