# Generated by Django 5.0.4 on 2026-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_historicallearn_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalourteam",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ourteam",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
