# Generated by Django 5.0.4 on 2025-10-31 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0036_alter_video_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="season",
            new_name="season_name",
        ),
        migrations.RemoveField(
            model_name="video",
            name="series",
        ),
        migrations.CreateModel(
            name="SeasonId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.CharField(max_length=100, unique=True)),
                (
                    "season_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_ids",
                        to="content.seasontitle",
                    ),
                ),
            ],
            options={
                "ordering": ("season_title__name",),
            },
        ),
        migrations.AddField(
            model_name="video",
            name="season_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.seasonid",
            ),
        ),
    ]
