# Generated by Django 5.0.4 on 2025-10-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0037_rename_season_video_season_name_remove_video_series_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonid",
            name="season_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="seasontitle",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
