# Generated by Django 5.0.4 on 2025-10-31 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0038_alter_seasonid_season_id_alter_seasontitle_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="season_id",
        ),
        migrations.AlterField(
            model_name="video",
            name="season_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.seasonid",
            ),
        ),
    ]
