# Generated by Django 5.0.4 on 2025-10-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0039_remove_video_season_id_alter_video_season_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="historyentry",
            name="image_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="weeklymoment",
            name="image_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
