# Generated by Django 5.0.4 on 2025-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0040_alter_event_image_url_alter_historyentry_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="historyentry",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="weeklymoment",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
