# Generated by Django 5.0.4 on 2025-11-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0041_alter_event_image_url_alter_historyentry_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
