# Generated by Django 5.0.4 on 2025-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0043_socialmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("position",),
            },
        ),
    ]
