# Generated by Django 5.0.4 on 2025-11-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0044_sectionorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="featured",
            new_name="is_featured",
        ),
    ]
