# Generated by Django 5.0.4 on 2025-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0045_rename_featured_video_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoWebSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=1000)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="social_media/logos/"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
