# Generated by Django 5.0.4 on 2025-11-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0046_infowebsite_delete_socialmedia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InfoWebSite",
        ),
    ]
