# Generated by Django 5.0.4 on 2025-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0048_navbarlogo_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                blank=True,
                choices=[("card", "Card"), ("photo", "Photo")],
                default="card",
                max_length=100,
            ),
        ),
    ]
