# Generated by Django 5.0.4 on 2025-11-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0050_contentcategory_eventcategory_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ("-created_at",)},
        ),
    ]
