# Generated by Django 5.0.4 on 2025-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0053_contentimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(max_length=100),
        ),
    ]
