# Generated by Django 5.0.4 on 2025-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0054_alter_video_video_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
