# Generated by Django 5.0.4 on 2025-11-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0055_alter_video_video_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_weekly_moment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_weekly_moment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_weekly_moment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="is_weekly_moment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=16,
            ),
        ),
    ]
