# Generated by Django 5.0.4 on 2025-11-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0056_content_is_weekly_moment_event_is_weekly_moment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=16,
            ),
        ),
    ]
