# Generated by Django 5.0.4 on 2025-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0057_alter_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
