# Generated by Django 5.0.4 on 2025-11-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0058_content_content_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeeklyMoment",
        ),
    ]
