# Generated by Django 5.0.4 on 2025-11-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0059_delete_weeklymoment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="metadata",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="content",
            name="subtitle",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
