# Generated by Django 5.0.4 on 2025-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0060_alter_content_metadata_alter_content_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
