# Generated by Django 5.0.4 on 2025-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0061_event_external_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentcategory",
            options={"ordering": ("order", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"ordering": ("order", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={"ordering": ("order", "-created_at")},
        ),
        migrations.AlterModelOptions(
            name="videocategory",
            options={"ordering": ("order", "-created_at")},
        ),
        migrations.AddField(
            model_name="contentcategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Manual ordering (lower values appear first)"
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Manual ordering (lower values appear first)"
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Manual ordering (lower values appear first)"
            ),
        ),
        migrations.AddField(
            model_name="videocategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Manual ordering (lower values appear first)"
            ),
        ),
    ]
