# Generated by Django 5.0.4 on 2025-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0062_alter_contentcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Accepts: .doc, .docx, .pdf, .ppt, .pptx",
                null=True,
                upload_to="content/attachments/",
            ),
        ),
    ]
