# Generated by Django 5.2.7 on 2025-12-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0065_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentattachment",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="content.content",
            ),
        ),
    ]
