# Generated by Django 5.0.4 on 2025-12-16 15:38

from django.db import migrations, models


def update_category_keys(apps, schema_editor):
    """Update existing categories with unique keys based on their ID to avoid duplicates."""
    PostCategory = apps.get_model('content', 'PostCategory')
    EventCategory = apps.get_model('content', 'EventCategory')
    ContentCategory = apps.get_model('content', 'ContentCategory')
    VideoCategory = apps.get_model('content', 'VideoCategory')
    BookCategory = apps.get_model('content', 'BookCategory')
    
    # Update PostCategory
    for category in PostCategory.objects.all():
        base_key = category.name.lower().replace(' ', '_').replace('-', '_')[:50]
        category.key = f"{base_key}_{category.id}"
        category.save()
    
    # Update EventCategory
    for category in EventCategory.objects.all():
        base_key = category.name.lower().replace(' ', '_').replace('-', '_')[:50]
        category.key = f"{base_key}_{category.id}"
        category.save()
    
    # Update ContentCategory
    for category in ContentCategory.objects.all():
        base_key = category.name.lower().replace(' ', '_').replace('-', '_')[:50]
        category.key = f"{base_key}_{category.id}"
        category.save()
    
    # Update VideoCategory
    for category in VideoCategory.objects.all():
        base_key = category.name.lower().replace(' ', '_').replace('-', '_')[:50]
        category.key = f"{base_key}_{category.id}"
        category.save()
    
    # Update BookCategory
    for category in BookCategory.objects.all():
        base_key = category.name.lower().replace(' ', '_').replace('-', '_')[:50]
        category.key = f"{base_key}_{category.id}"
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0067_bookcategory_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcategory",
            name="key",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bookcategory",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contentcategory",
            name="key",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contentcategory",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="key",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="key",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="videocategory",
            name="key",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="videocategory",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        # Run Python function to update keys before applying unique constraints
        migrations.RunPython(update_category_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="bookcategory",
            name="name",
            field=models.CharField(
                help_text="Category name in the specified language", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="contentcategory",
            name="name",
            field=models.CharField(
                help_text="Category name in the specified language", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="name",
            field=models.CharField(
                help_text="Category name in the specified language", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.CharField(
                help_text="Category name in the specified language", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="videocategory",
            name="name",
            field=models.CharField(
                help_text="Category name in the specified language", max_length=100
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookcategory",
            unique_together={("key", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="contentcategory",
            unique_together={("key", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="eventcategory",
            unique_together={("key", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="postcategory",
            unique_together={("key", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="videocategory",
            unique_together={("key", "language")},
        ),
        migrations.AddIndex(
            model_name="bookcategory",
            index=models.Index(
                fields=["key", "language"], name="content_boo_key_7c3903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentcategory",
            index=models.Index(
                fields=["key", "language"], name="content_con_key_e0e6dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(
                fields=["key", "language"], name="content_eve_key_a28445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcategory",
            index=models.Index(
                fields=["key", "language"], name="content_pos_key_afa047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocategory",
            index=models.Index(
                fields=["key", "language"], name="content_vid_key_d222d4_idx"
            ),
        ),
    ]
