# Generated by Django 5.2.7 on 2025-12-25 12:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_add_multilanguage_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventsection',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default='en', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyentry',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default='en', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyentry',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='positionteammember',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasontitle',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ch', 'Chinese'), ('jp', 'Japanese'), ('chsi', 'Chinese Simplified')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='historyentry',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('translation_group', 'language')},
        ),
    ]
