# Generated by Django 5.0.4 on 2025-12-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0068_add_multilanguage_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasonid",
            name="season_title",
        ),
        migrations.RemoveField(
            model_name="video",
            name="season_name",
        ),
        migrations.DeleteModel(
            name="SeasonTitle",
        ),
        migrations.DeleteModel(
            name="SeasonId",
        ),
    ]
