# Generated by Django 5.0.4 on 2025-12-27 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0068_add_multilanguage_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcategory",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same category",
            ),
        ),
        migrations.AddField(
            model_name="contentcategory",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same category",
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same category",
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same category",
            ),
        ),
        migrations.AddField(
            model_name="videocategory",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same category",
            ),
        ),
    ]
