# Generated by Django 5.2.7 on 2025-12-25 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_book_language_book_translation_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
