# Generated by Django 5.2.7 on 2026-01-07 06:59

import uuid
from django.db import migrations, models


def assign_translation_groups(apps, schema_editor):
    models_to_update = (
        "Event",
        "EventSection",
        "PositionTeamMember",
        "SeasonTitle",
    )

    for model_name in models_to_update:
        Model = apps.get_model("content", model_name)
        objects = Model.objects.all().only("pk")
        for obj in objects.iterator():
            Model.objects.filter(pk=obj.pk).update(translation_group=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_bookcategory_translation_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventsection',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='positionteammember',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='seasontitle',
            name='translation_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(assign_translation_groups, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='eventsection',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='positionteammember',
            unique_together={('translation_group', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='seasontitle',
            unique_together={('translation_group', 'language')},
        ),
    ]
