# Generated by Django 5.0.4 on 2025-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0070_alter_bookcategory_key_alter_contentcategory_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcategory",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contentcategory",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="videocategory",
            name="key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique identifier for this category across all languages",
                max_length=100,
            ),
        ),
    ]
