# Generated by Django 5.0.4 on 2025-12-27 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0071_alter_bookcategory_key_alter_contentcategory_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="translation_group",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID grouping translations of the same video",
            ),
        ),
    ]
