# Generated by Django 5.0.4 on 2026-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0072_video_translation_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_clip", "New Clip"),
                    ("full_live_stream", "Full Live Stream"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
