# Generated by Django 5.0.4 on 2026-01-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0072_video_translation_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionorder",
            name="key",
        ),
    ]
