# Generated by Django 5.0.4 on 2026-01-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0073_remove_sectionorder_key"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postcategory",
            name="content_pos_key_afa047_idx",
        ),
        migrations.AlterUniqueTogether(
            name="postcategory",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="postcategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="postcategory",
            name="translation_group",
        ),
    ]
