# Generated by Django 5.0.4 on 2026-01-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0074_remove_postcategory_content_pos_key_afa047_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookcategory",
            name="content_boo_key_7c3903_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentcategory",
            name="content_con_key_e0e6dc_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventcategory",
            name="content_eve_key_a28445_idx",
        ),
        migrations.RemoveIndex(
            model_name="videocategory",
            name="content_vid_key_d222d4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="bookcategory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="contentcategory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="eventcategory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="videocategory",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="video",
            name="translation_group",
        ),
        migrations.RemoveField(
            model_name="bookcategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="bookcategory",
            name="translation_group",
        ),
        migrations.RemoveField(
            model_name="contentcategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="contentcategory",
            name="translation_group",
        ),
        migrations.RemoveField(
            model_name="eventcategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="eventcategory",
            name="translation_group",
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="translation_group",
        ),
    ]
