# Generated by Django 5.0.4 on 2026-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0074_learncategory_learn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="comment",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="user",
        ),
        migrations.RemoveField(
            model_name="video",
            name="translation_group",
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
