# Generated by Django 5.0.4 on 2026-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0075_remove_bookcategory_content_boo_key_7c3903_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcategory",
            name="source_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Turkish"),
                    ("ar", "Arabic"),
                    ("ch", "Chinese"),
                    ("jp", "Japanese"),
                    ("chsi", "Chinese Simplified"),
                ],
                default="en",
                help_text="The source language for this category",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postcategory",
            name="translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores translations for all languages: {lang: {name, description, is_source, auto_translated}}",
            ),
        ),
    ]
