# Generated by Django 5.0.4 on 2026-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0075_remove_reply_comment_alter_like_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="postrating",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="learn",
            name="writer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="PostCategory",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostRating",
        ),
    ]
