# Generated by Django 5.0.4 on 2026-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0076_remove_post_category_remove_postrating_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learn",
            name="happened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
