# Generated by Django 5.0.4 on 2026-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0077_learn_happened_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="learncategory",
            constraint=models.UniqueConstraint(
                fields=("name", "learn_type"), name="unique_learncategory_name_per_type"
            ),
        ),
    ]
