# Generated by Django 5.0.4 on 2026-02-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0078_learncategory_unique_learncategory_name_per_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learn",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learns",
                to="content.learncategory",
            ),
        ),
    ]
