# Generated by Django 5.0.4 on 2026-02-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0079_alter_learn_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learn",
            name="body",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="camera_name",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="country",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="language",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="read_time",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="status",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="writer",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="writer_avatar",
        ),
    ]
