# Generated by Django 5.0.4 on 2026-02-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0080_remove_learn_body_remove_learn_camera_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="cast",
            new_name="guest_speakers",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="thumbnail_url",
            new_name="live_stream_link",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_weekly_moment",
        ),
        migrations.RemoveField(
            model_name="video",
            name="season_name",
        ),
        migrations.RemoveField(
            model_name="video",
            name="status",
        ),
        migrations.RemoveField(
            model_name="video",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="video",
            name="thumbnail",
        ),
    ]
