# Generated by Django 5.0.4 on 2026-02-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0081_rename_cast_video_guest_speakers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learn",
            name="direction",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="VideoAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="videos/materials/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="content.video",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
