# Generated by Django 5.0.4 on 2026-02-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0082_learn_direction_videoattachment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videocategory",
            name="content_vid_key_d222d4_idx",
        ),
        migrations.AlterUniqueTogether(
            name="videocategory",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="key",
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="language",
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="translation_group",
        ),
    ]
