# Generated by Django 5.0.4 on 2026-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0083_remove_videocategory_content_vid_key_d222d4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learn",
            name="is_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="videos/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="live_stream_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
