# Generated by Django 5.0.4 on 2026-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0084_learn_is_event_video_thumbnail_video_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="live_stream_link",
        ),
        migrations.AddField(
            model_name="learn",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learn",
            name="event_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learn",
            name="event_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="learn",
            name="guest_speakers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="learn",
            name="live_stream_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
