# Generated by Django 5.0.4 on 2026-02-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0085_remove_video_live_stream_link_learn_event_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoAttachment",
        ),
    ]
