# Generated by Django 5.0.4 on 2026-02-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0086_delete_videoattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentattachment",
            name="Video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="content.video",
            ),
        ),
    ]
