# Generated by Django 5.0.4 on 2026-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0087_contentattachment_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learn",
            name="direction",
        ),
        migrations.AddField(
            model_name="learncategory",
            name="direction",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
