# Generated by Django 5.0.4 on 2026-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0088_remove_learn_direction_learncategory_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_type",
            field=models.CharField(
                blank=True,
                choices=[("clip_video", "Clip Video"), ("full_video", "Full Video")],
                max_length=100,
                null=True,
            ),
        ),
    ]
