# Generated by Django 5.0.4 on 2026-02-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0089_alter_video_video_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeasonId",
        ),
        migrations.DeleteModel(
            name="SeasonTitle",
        ),
    ]
