# Generated by Django 5.0.4 on 2026-02-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0090_delete_seasonid_delete_seasontitle"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentRating",
        ),
    ]
