# Generated by Django 5.0.4 on 2026-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0091_delete_contentrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learncategory",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("horizontal", "Horizontal"), ("vertical", "Vertical")],
                max_length=255,
            ),
        ),
    ]
