# Generated by Django 5.0.4 on 2026-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0092_alter_learncategory_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_url",
        ),
    ]
