# Generated by Django 5.0.4 on 2026-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0093_remove_video_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
