# Generated by Django 5.0.4 on 2026-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0094_video_thumbnail_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learn",
            old_name="event_date",
            new_name="end_event_date",
        ),
        migrations.RenameField(
            model_name="learn",
            old_name="event_time",
            new_name="end_event_time",
        ),
        migrations.AddField(
            model_name="learn",
            name="start_event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learn",
            name="start_event_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
