# Generated by Django 5.0.4 on 2026-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0095_rename_event_date_learn_end_event_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learn",
            name="end_event_date",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="end_event_time",
        ),
        migrations.AddField(
            model_name="learn",
            name="duration",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
