# Generated by Django 5.0.4 on 2026-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0096_remove_learn_end_event_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCommunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("guest_speakers", models.JSONField(blank=True, default=list)),
                ("start_event_date", models.DateField(blank=True, null=True)),
                ("start_event_time", models.TimeField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "ordering": ("-start_event_date", "-start_event_time"),
            },
        ),
        migrations.RemoveField(
            model_name="learn",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="event_title",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="guest_speakers",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="start_event_date",
        ),
        migrations.RemoveField(
            model_name="learn",
            name="start_event_time",
        ),
    ]
