# Generated by Django 5.0.4 on 2026-02-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0097_eventcommunity_remove_learn_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcommunity",
            name="learn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.learn",
            ),
        ),
    ]
