# Generated by Django 5.0.4 on 2026-02-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0098_eventcommunity_learn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcommunity",
            name="learn",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__learn_type": "posters"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.learn",
            ),
        ),
    ]
