# Generated by Django 5.0.4 on 2026-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0099_alter_eventcommunity_learn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.RemoveField(
            model_name="event",
            name="section",
        ),
        migrations.DeleteModel(
            name="EventCategory",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventSection",
        ),
    ]
