# Generated by Django 5.0.4 on 2026-02-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0100_remove_event_category_remove_event_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="category",
        ),
        migrations.RemoveField(
            model_name="contentimage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="contentattachment",
            name="content",
        ),
        migrations.DeleteModel(
            name="ContentCategory",
        ),
        migrations.DeleteModel(
            name="ContentImage",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
    ]
