# Generated by Django 5.0.4 on 2026-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0101_remove_content_category_remove_contentimage_content_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learn",
            name="live_stream_link",
        ),
        migrations.AddField(
            model_name="eventcommunity",
            name="live_stream_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
