# Generated by Django 5.0.4 on 2026-03-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0102_remove_learn_live_stream_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcommunity",
            name="learn",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__learn_type": "posters"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_communities",
                to="content.learn",
            ),
        ),
    ]
