# Generated by Django 5.0.4 on 2026-03-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0103_alter_eventcommunity_learn"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookcategory",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="BookCategory",
        ),
    ]
