# Generated by Django 5.0.4 on 2026-03-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0104_alter_bookcategory_unique_together_delete_book_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoryEntry",
        ),
        migrations.DeleteModel(
            name="SectionOrder",
        ),
    ]
