# Generated by Django 5.0.4 on 2026-03-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0105_delete_historyentry_delete_sectionorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="position",
        ),
        migrations.DeleteModel(
            name="PositionTeamMember",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
