# Generated by Django 5.0.4 on 2026-03-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0108_photocollection_photo"),
        ("content", "0108_photocollection_photo_and_more"),
    ]

    operations = []
