export const getSectionKey = (title) => {
  const titleMap = {
    Home: "home",
    Read: "read",
    "All Posts": "posts",
    "Add/Edit Post": "createOrEditPost",
    "Posts Categories": "postsCategories",
    "All Videos": "videos",
    "All Cards": "cards",
    Videos: "videos",
    "Videos Categories": "videosCategories",
    "Add New Video": "createOrEditVideo",
    "Series & Seasons": "seriesAndSeasons",
    "Videos Seasons": "videosSeasons",
    History: "history",
    "Our Team": "team",
    "Health Posts": "healthPosts",
    "News List": "newsList",
    "Add/Edit News": "createOrEditNews",
    "News Categories": "newsCategories",
    "Events List": "eventsList",
    "Add/Edit Event": "createOrEditEvent",
    "Events Categories": "eventsCategories",
    "Events Sections": "eventsSections",
    "Profile Settings": "profileSettings",
    profile: "profile",
    "Social Media": "socialMedia",
    "Sort Section": "sortSection",
    team: "team",
    positions: "positions",
  };
  return titleMap[title] || title.toLowerCase();
};
